language: php
php:
- 5.6
script:
- .travis/deploy.sh
branches:
  only:
  - develop
before_install:
- openssl aes-256-cbc -K $encrypted_acc199b18d38_key -iv $encrypted_acc199b18d38_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
